### ISSUE TITLE
ERB tag styles?

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#10]
One (relatively minor) thing I see us doing differently across several of our apps is the indentation of embedded Ruby tag openers/closers when the contents of the tag spans multiple lines. The three styles I can think of:

```
<% some_long_ruby
  some_more_long_ruby %>

<% some_long_ruby
  some_more_long_ruby
%>

<%
  some_long_ruby
  some_more_long_ruby
%>
```

Personally, my least favorite is the first, though it also seems to be the most widely-used. I'd say I like the last one the most, though I also see it the least. It seems most similar to how we typically indent multi-line hashes or method calls.

**Comment by emerson-h** [comment]
I like the last one the most. I suggest we adopt that for new code.

**Comment by mjs2600** [comment]
:+1: for the last one.

**Comment by adam-scimed** [comment]
Anyone opposed?

Andy, would you update the style guide?

Thanks!

--
Adam Stasio
SciMed Solutions
327 West Main Street
Durham, NC 27701

adam.stasio@scimedsolutions.com
(919) 287-1817
(919) 680-3377 - Fax
--

**Comment by andycandrea** [comment]
Resolved in 60bdd11.

**Comment by mjs2600** [comment]
As final thought before we standardize this: I think this might be a code smell to have more than one line of code in an ERB tag. I know that there's cases where it makes sense, but I just wanted to point that out.

**Comment by josephjaber** [comment]
@mjs2600 :+1: :+1: :+1:

**Comment by andycandrea** [comment]
:+1: I'll make sure that's reflected in the guide.
