### ISSUE TITLE
too-long classes/modules

### ISSUE THREAD

**Issue by andreaangott** [SciMed/style-guide#105]
When classes/modules are over the length enforced by Rubocop (and this length is judged to be reasonable for the context), I believe we have an internal convention of disabling that rule by adding the file to the `Exclude` list for `Metrics/ClassLength` or `Metrics/ModuleLength` in `.rubocop.yml` instead of disabling the rule inline.

Is this a convention we like?  If so, it probably make sense to document it somewhere.

**Comment by andycandrea** [comment]
We have decided that we like this convention and will document it in the style guide under the "Adhere to rubocop" bullet point.
