### ISSUE TITLE
data attribute formatting

### ISSUE THREAD

**Issue by andreaangott** [SciMed/style-guide#109]
Proposal: let's document a standard formatting for HTML data attributes.  I'll propose standardizing on using `-` as word separators and not `_`.  

(I've recently run into a bug due to inconsistency in this domain)

**Comment by andycandrea** [comment]
Under your proposed standard, would using underscores in Rails helper methods be permissible a la:

```rb
link_to(
  'something',
  'somewhere',
  data: { my_attribute: true }
)
```

Or would the following be preferred?

```rb
link_to(
  'something',
  'somewhere',
  data: { 'my-attribute': true }
)
```

**Comment by andreaangott** [comment]
Ah, the thing I'd like to standardize is the actual data attribute name in the DOM.  The former syntax yields `data-my-attribute` as the name so I'm cool with that.

**Comment by andycandrea** [comment]
Okay, great--thanks what I figured you meant, but I wanted to be extra sure.

**Comment by andycandrea** [comment]
We'll add this to the style guide.
