### ISSUE TITLE
Add standard method for accessing current time to style guide

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#11]
There seem to be three common methods for grabbing the current time: `Time.now`, `Time.current` and `Time.zone.now`, each of which has its pros and cons.

`Time.now`
Pros:
* Most common across our applications
* Short and sweet
Cons:
* Doesn't include a time zone, which can cause undesired behavior when comparing to Rails timestamps that are stored in UTC.
* Rubocop complains

`Time.current`
Pros:
* Pretty short and straight forward
* Equivalent to `Time.zone.now` when `Time.zone` is set but shorter/easier to type
Cons:
* Equivalent to `Time.now` when `Time.zone` is not set
* As a result of the above, it'll return different types of objects in different contexts

`Time.zone.now`
Pros:
* Converts properly to UTC to the set `Time.zone`
Cons:
* Requires the `Time.zone` to be set (to behave as expected, at least)
* Long relative to the others
* I remember someone mentioning they've had trouble with `Time.zone.now` in the past, but I don't remember the details

**Comment by adam-scimed** [comment]
It sounds like Time.zone.now is the winner, at least for now!
