### ISSUE TITLE
Change rubocop config for Layout/LineEndStringConcatenationIndentation?

### ISSUE THREAD

**Issue by andreaangott** [SciMed/style-guide#112]
The default configuration is `EnforcedStyle: aligned`, which wants this:

```rb
        flash.now[:error] = 'There was a problem sending password reset'\
                            "instructions: #{e.message}"
```

The configuration of `EnforcedStyle: indented` seems more space-efficient to me.  It wants this:

```rb
        flash.now[:error] = 'There was a problem sending password reset'\
          "instructions: #{e.message}"
```

**Comment by andycandrea** [comment]
We're considering turning this cop off but will wait until more of the team has had the change to weigh in.

**Comment by andycandrea** [comment]
We will changed it to `Indented` for now and will consider turning it off in the future if anyone has any issues.
