### ISSUE TITLE
Proposed config for new eslint rule, `react/function-component-definition`

### ISSUE THREAD

**Issue by andreaangott** [SciMed/style-guide#117]
Details here: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md

I propose adding this config to our `.eslintrc`:

```
"react/function-component-definition": [2, { "namedComponents": "arrow-function" }]
```

**Comment by andycandrea** [comment]
We will add this to the eslintrc.
