### ISSUE TITLE
Double or single quotes in HTML?

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#12]
This is something that we don't have a consensus on, so I feel like it's worth discussing and integrating into the style guide. The issue is the following:

```
<div class='foo'></div>
```
versus
```
<div class="foo"></div>
```

Here are the pros that have come up for each thus far:
Single quotes:
* Consistent with our ERB and the rest of our application

Double quotes:
* More common in HTML

**Comment by stevenspiel** [comment]
In an official poll at SciMed retrospective, we decided on double quotes.
