### ISSUE TITLE
Whitespace in specs

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#14]
This is something that I feel varies widely both between and within projects. Before he left, Max and I came up with a standard that the two of us adopted (and then failed to document anywhere).

Here's an example:

```
require spec_helper

RSpec.describe Foo do
  let(:bar) { 'bar' }

  subject { described_class.new }

  describe '.some_class_method' do
    let(:bar2) { 'bar2' }
    let(:bar3) { 'bar3' }

    subject { described_class }

    before do
      visit foos_path
    end

    context 'when buzz' do
      it 'does something' do
        ...
      end
      it 'does something else' do
        ...
      end
    end

    context 'when fizz' do
      ...
    end
  end

  describe '#some_instance_method' do
    ...
  end
end
```

Basically, the rules are the following:
1. Put a single line of whitespace between sibling `context` and `describe` blocks.
1. Put no whitespace between sibling `let`, `it` or `scenario` blocks
1. Put a line of whitespace between different types of sibling blocks ("type" being a `let` or a `subject`, for example, where `let` and `let!` were considered the same).

**Comment by josephjaber** [comment]
:+1:

**Comment by kathleenlan** [comment]
I also agree with the rules you suggested. :+1: 

Thanks for documenting this!

**Comment by adam-scimed** [comment]
Approved
