### ISSUE TITLE
Multiline `%` arrays

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#16]
In general, it seems like we're moving more towards utilizing `%w()` and `%i()` over the literal array syntax. While I definitely like this trend (especially since it's supported by [the Ruby style guide](https://github.com/bbatsov/ruby-style-guide#percent-w)), the distinction between elements in larger arrays can be a little unclear. For example:

```
%w(
  car banana_cat dog apple foo bar scimed_solutions
  scimed car apple_car bar_solutions banana dog foo
)
```

Emerson proposed having a single element per line in these types of situations like:

```
%w(
  car
  banana_cat
  dog
  apple
  foo
  bar
  scimed_solutions
  scimed
  car
  apple_car
  bar_solutions
  banana
  dog
  foo
)
```

Even though this will often lead to a `Metrics/MethodLength` violation in Rubocop, I also think this looks a little better. Thoughts from everyone else?

**Comment by kathleenlan** [comment]
This suggestion seems fine to me.

I don't think the Metrics/MethodLength violation is a concern. Presumably, a longer multiline array will be extracted into its own method. In that case, it seems like it would be appropriate to disable the Metrics/MethodLength cop for that method, since this rubocop violation seems comparable to those commonly seen in strong parameter methods, e.g. methods like

```
def permitted_params
  params.require(:my_things).permit(
    car,
    banana_cat,
    dog,
    apple,
    foo,
    bar,
    scimed_solutions,
    scimed,
    car,
    apple_car,
    bar_solutions,
    banana,
    dog,
    foo
  )
end
```

and in at least one project, we're already disabling Metrics/MethodLength for strong parameter methods (which makes sense).

So if we decide to accept this style guideline for multiline arrays, I propose disabling the Metrics/MethodLength cop.

**Comment by mjs2600** [comment]
I wish we could count method calls instead of lines. My understanding is that the rule is the there to control method complexity, not actual lines of code.

**Comment by mjs2600** [comment]
I'm a little concerned about giving up monitoring method size altogether. If we decide to go this way, I think we should raise the upper bound rather than removing it. I don't see any situation where a 100 line method is justifiable.

**Comment by emerson-h** [comment]
Method length should be an opt-out cop for long array methods rather than off completely in my opinion.  If we find that we have so many multi-line array literals that it's painful to opt them out then I think that's symptomatic of some other problem.

**Comment by andreaangott** [comment]
I really like multi-line arrays.  I think they're easier to visually parse,
and don't think all the array's lines should be counted against the
method's line count.

Mike: I think Kathleen was suggesting that the rule be manually disabled on
a per-method basis with the `# rubocop:disable Metrics/MethodLength` syntax.


On Wed, Jan 6, 2016 at 8:45 AM, Michael Simpson <notifications@github.com>
wrote:

> I'm a little concerned about giving up monitoring method size altogether.
> If we decide to go this way, I think we should raise the upper bound rather
> than removing it. I don't see any situation where a 100 line method is
> justifiable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SciMed/style-guide/issues/16#issuecomment-169326220>.
>



-- 

*Andrea Angott*

SciMed Solutions

327 West Main Street

Durham, NC 27701

andrea.angott@scimedsolutions.com

(919) 287-1817 x312 – phone

(919) 680-3377 – fax

**Comment by mjs2600** [comment]
@andreaangott Ahh, that makes sense!

**Comment by emerson-h** [comment]
@andreaangott Yes that does make sense :+1:

**Comment by kathleenlan** [comment]
:+1: Andrea

**Comment by kathleenlan** [comment]
In a WTL, we decided to write the arrays on a single line if it's less than 80 characters and on one line per word otherwise.
