### ISSUE TITLE
Unused controller methods corresponding to used routes

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#17]
@andreaangott brought up a good point that I think is missed in our current guide. For example, let's say we have a `show` action in our `FoosController` that doesn't need any code to be run aside from the template rendering and routing. We could either have the following example:

```
class FoosController < ApplicationController
  def show
  end
end
```

Or we could just not have any `def show` whatsoever.

I'm personally not sure which I prefer. I like removing code that doesn't have any functionality, but, when I'm reading a controller, I like all the logic to be presented clearly. I think having the empty `def` can be useful so I don't try to see if it's actually defined elsewhere or if I'm in the wrong controller.

Thoughts?

**Comment by andreaangott** [comment]
Personally, I feel like it clutters up the controller.  Such "empty" actions are still defined in the routes; in my opinion, that's sufficient.

**Comment by adam-scimed** [comment]
I (personally) like having them there. When I look for how things are wired together I look in the controller, but don't look in the routes very often. If something like that is in the controller then I instantly know what is happening.

Also, I wish that it was required to have each method listed in the controller for it to respond. I think that would make things more clear and also avoid security issues if there is a route that allows access to something it shouldn't.

That said, if everyone else thinks it's clear enough with actions defined in the routes, then removing clutter is always good!

**Comment by kathleenlan** [comment]
In a WTL, we decided to keep empty controller action definitions.
