### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by adam-scimed** [SciMed/style-guide#18]
We have a pretty good standard for where to put documentation, but I think we might need one or two clarifications, and it probably makes sense to put that standard in the style-guide.

We may have documentation stored in various places for different reasons. That is fine, but I would suggest that any documentation be referred to in the project README.md. No matter where the documentation is, you should be able to find it by reading the README.

On some projects the README is at the root. On other projects it is in the docs/ folder. I would recommend that we always keep it at the root since that seems to be the Rails standard. Also the README at the root is displayed on the GitLab home page for the project. Feel free to put other documentation in the docs/ folder and refer to it from the /README.md.

Any thoughts on this?

**Comment by mjs2600** [comment]
:+1:

**Comment by andycandrea** [comment]
Didn't we decide to keep the `README` in the `docs/` folder a few months ago at a retrospective or WTL? That said, I don't exactly remember why we chose to do that. I personally like having the `README` in the root as well.

**Comment by kathleenlan** [comment]
:+1:

**Comment by kathleenlan** [comment]
In a training lunch we decided on the following:

* Keep the `README` in the project root directory
* Use markdown in the `docs/` folder for documentation
* Prefer `README` and `docs/` over the wiki
* If documentation exists elsewhere, link to it from the `README`
