### ISSUE TITLE
externalize customer-facing strings such as error messages, HTML text

### ISSUE THREAD

**Issue by anicholson44** [SciMed/style-guide#22]
We should discuss moving customer-facing strings to external configuration files so that it is easy to change them with client feedback.

**Comment by andycandrea** [comment]
I definitely feel that this is worth discussing, though it's not something I have much experience with. Perhaps things like this could go into i18n config files?

**Comment by josephjaber** [comment]
You could use localization. I would define two languages. "Brutally Honest" and "Customer". Then for the Brutally Honest version you could give everything names like, "Pointless Feature". For the Customer language version you could then translate the brutally version, e.g. "Reporting Page".

**Comment by tyleramos** [comment]
I see a lot of "Pointless Feature"s getting created :)

**Comment by fatcatt316** [comment]
If no messages ever reach the customer, there wouldn't be this problem. I'd recommend not showing them any strings at all. Maybe emojis?

**Comment by adam-scimed** [comment]
It seems that localization is the standard Rails way of handling this, even if you don't need to support multiple languages. I would recommend we make use of that as a solution whenever we want to move customer-facing text out of the code (which is always?).

**Comment by kathleenlan** [comment]
In WTL, we agreed to use a localization config file, but we need to flesh out the details of when to use this. Let's also add an example for what this would look like for error messages on a nested/associated record.

**Comment by kathleenlan** [comment]
General rules for when to use a localization config file:

* When the text is likely to change frequently
* When the text is a template that is used in multiple places (i.e. to keep the code dry)
