### ISSUE TITLE
Limit spec runs with focus tag by default

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#25]
In most of our older applications, we have the following enabled in our `spec_helper`:

```
config.filter_run :focus
config.run_all_when_everything_filtered = true
```

I've noticed that a lot of the newer applications/gems that we've created haven't included this by default. Personally, I use this almost every time that I'm working on tests (which is almost every day), so I've been enabling it in our new projects whenever I see it's missing or commented out. Anyone have objections to me doing this by default?

**Comment by mjs2600** [comment]
:+1: even though guard is better :stuck_out_tongue:

**Comment by kathleenlan** [comment]
:+1: sounds good to me, too

**Comment by dbernheisel** [comment]
Seems like a developer preference, which is a-ok with me, but maybe not the place for the style guide, and I promise not to remove them from your projects ;)
