### ISSUE TITLE
Immediately add new gems/applications to CI

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#26]
I can't imagine there's much controversy here, but it'd be nice to specify this in the style guide as a reminder. Search Drive for "How to Set Up Projects on CI" if you need directions.

**Comment by kathleenlan** [comment]
Sounds good to me. :+1:

**Comment by andycandrea** [comment]
Maybe it would make sense to add a whole section about creating new applications/gems? It could mention including Rubocop, setting the project up on CI, etc.

**Comment by mjs2600** [comment]
:+1:
