### ISSUE TITLE
Prefer `has_one/many through` associations over delegations

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#27]
I've been seeing this pattern a lot lately:

```
class Foo
  belongs_to :bar
end

class Bar
  has_one :foo
  has_one :baz
end

class Baz
  delegate :foo, to: :bar

  belongs_to :bar
end
```

Personally, I'd prefer to see the following:

```
class Foo
  belongs_to :bar
end

class Bar
  has_one :foo
  has_one :baz
end

class Baz
  belongs_to :bar
  has_one :foo, through: :bar
end
```
### Advantages:
1. Built-in handling for the case where `baz.bar` is `nil`.
2. By default, calling `baz.foo` generates one query; when we're delegating, it generates one query to load the intermediate `bar` and then another query to get the `foo`. This is, I think, the biggest advantage since it seems like there tend to be many places in our code where we forget to use `includes`.
3. If our intention is to grab the `foo`, we can prevent n+1 queries with `Baz.includes(:foo)` rather than having to do `Baz.includes(bar: :foo)`.
### Disadvantages:
1. This doesn't work as well for in-memory associations. If the `foo`, `bar` and `baz` are not yet persisted, calling `baz.foo` will give `nil` if we use the `has_one through`; it'll give the in-memory object with the delegation.

Since Rails already makes us handle in-memory associations manually, I don't see the disadvantage as being a huge downside. Plus, we could always have the following if we really wanted access to the in-memory object with one method call:

```
class Baz
  delegate :foo, to: :bar, prefix: :in_memory

  belongs_to :bar
  has_one :foo, through: :bar
end
```

**Comment by kathleenlan** [comment]
I don't have a strong opinion on this, but what you said sounds reasonable to me. I would be fine with preferring has_one/has_many through: over delegate. :+1:

**Comment by mjs2600** [comment]
👍

**Comment by dbernheisel** [comment]
Looks great! Let's do it.

**Comment by kathleenlan** [comment]
Emerson has concerns about `has_one` adding instantiation methods in cases where the associated model is several models away.

We are going to table this until Andy returns.

**Comment by adam-scimed** [comment]
Consider what you're doing before you choose. Each has it's own advantages/disadvantages.

@andycandrea - Could you add a few examples of each method and the pros and cons and add them to the style guide?
