### ISSUE TITLE
Determine strategy for handling irregular nouns in rails

### ISSUE THREAD

**Issue by anicholson44** [SciMed/style-guide#28]
Sometimes Rails is wrong about how to pluralize a model name. Should we go with the Rails default, or should we write our own Inflector? What about in cases like 'MediumOrDiet' where the model name is really two nouns, and Rails only pluralizes the second?

**Comment by andycandrea** [comment]
Sticking with the default is definitely simpler, and it's what I favor for existing applications. That said, I wouldn't be opposed to writing proper pluralization on new projects going forward--we'll just want to make sure that we're consistent if we do.

**Comment by mjs2600** [comment]
👍  to what @andycandrea said.

**Comment by adam-scimed** [comment]
Rails has had some bugs in the past that made custom inflectors a bit painful. It has been a while, so I would recommend that we try custom inflectors again the next time you need them. Theoretically they are the right answer -- they result in things being named properly. If you try an inflector and it is painful, let us know and we will revert to using defaults inflections!
