### ISSUE TITLE
For discussion: Standardizing per JSON API specification

### ISSUE THREAD

**Issue by andreaangott** [SciMed/style-guide#29]
What do you guys think about standardizing future JSON responses we develop per the [JSON API specification](http://jsonapi.org/format/)?  Let's talk.

**Comment by dbernheisel** [comment]
We've used this in a couple projects, and it seems low-risk with potentially high-rewards later when we establish good practices with a front-end structure and other clients that directly consume JSON APIs.  I think it would be best to use this JSONApi standard for new projects going forward, and older projects stay consistent.

**Comment by dbernheisel** [comment]
For later reference, gems that help Rails apps manage JSONApi:
https://github.com/cerebris/jsonapi-resources
https://github.com/rails-api/active_model_serializers

**Comment by kathleenlan** [comment]
Apparently, at the last style guide meeting, Adam recommended that we try this out on a few projects before making a decision.

**Comment by kathleenlan** [comment]
Emerson noted that we should keep our JSON structure as shallow as possible, in keeping with best practices.

**Comment by adam-scimed** [comment]
We are going to review the merge request (closing this issue)
