### ISSUE TITLE
Testing JSON

### ISSUE THREAD

**Issue by andreaangott** [SciMed/style-guide#30]
I propose adding something to our testing section about testing JSON generated by our apps.  I like [Thoughtbot's approach](https://robots.thoughtbot.com/validating-json-schemas-with-an-rspec-matcher) of testing against a JSON schema.  Thoughts?

**Comment by dbernheisel** [comment]
I think this is a great idea and mirrors our approach to testing the database schema; it would be awesome if we could put together an example of this JSON schema validation as well as an equivalent XML schema validation (w/ DTD).

Whenever the output structure changes, this test will prompt us to update the tests or catch whatever changed the structure.

**Comment by kathleenlan** [comment]
Andrea will add something to the style guide regarding this issue.
