### ISSUE TITLE
What javascript package manager should we use?

### ISSUE THREAD

**Issue by kathleenlan** [SciMed/style-guide#31]
From the styleguide:

```
Use a package manager like Bower for installing dependencies? (This item is questionable as some people raised issues with using Bower with Rails. We can discuss further.)
```

**Comment by dbernheisel** [comment]
I think we've determined that `npm` is preferred over Bower and rails-assets.org for getting libraries into the project. The React community seems to have rallied around [Webpack](https://webpack.github.io/) as the pipeline manager afterwards, but are still figuring that side out.

**Comment by kathleenlan** [comment]
Add a section to the style guide regarding this issue.
