### ISSUE TITLE
code documentation preferred format

### ISSUE THREAD

**Issue by andreaangott** [SciMed/style-guide#32]
Should we add a note about our preferred code documentation format?  Confirm that YARD is the consensus? (http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md) Add some helpful tidbits/highlights?  E.g., @andycandrea mentioned that the following bits are useful:
```
# Syntax for a method that can return multiple types
@return [String, nil]

# Syntax for a method that returns a collection
@return [Array<String>]

# Syntax for a method with a non-meaningful return value
@return[void]
```

**Comment by kathleenlan** [comment]
We have all agreed to use YARD for documentation. @emerson-h will add this to the style guide.
