### ISSUE TITLE
Consider using 'describe', 'context', and 'it' in Capybara tests instead of 'feature' and 'scenario'

### ISSUE THREAD

**Issue by anicholson44** [SciMed/style-guide#34]
I've run into a few problems with using `feature` and `scenario` in capybara tests.
1. Most practical reason (probably only applies to RubyMine devs, though that is a significant chunk of our team) - RubyMine cannot run a single test in a file if the test uses `scenario` instead of `it`, it only knows how to run the whole test file, which can take a while longer and make it more tedious to isolate one test
2. Using `scenario` instead of both `context` and `it`, we end up putting information about the context in the `scenario` statement, as well as sometimes information about what the expected behavior is (and sometimes we omit the expected behavior). We are familiar with `context` and `it` and both of them together give us better designed tests. One important functional difference between `scenario` and using `context` and `it` is that you cannot put `let`, `before`, or `subject` blocks in a `scenario`. We could mitigate this by using `context` outside of our `scenario` blocks, but it doesn't look like we're doing that in practice.
3. Why not be consistent with our semantics across all tests? It would make things easier on beginners and reduce context-switching costs between rspec and capybara tests.

**Comment by josephjaber** [comment]
I prefer `nonsense` and `shenanigans` blocks, just no `hankypanky` blocks. Those should only be used for brittle tests.

**Comment by fatcatt316** [comment]
Automated tests make developers lazy, and lead them to skip manually testing changes. I'd vote to just delete them all. This has the added bonus of speeding up Jenkins.

**Comment by anthonylebrun** [comment]
Steps to fix:

- Replace with MiniTest
- #Winning

**Comment by stevenspiel** [comment]
What are the downsides of using feature? I only see mention of scenario.

**Comment by stevenspiel** [comment]
And it's good to hear that a "significant portion" of the dev team is using
Rubymine. The rest of you: why do you persist in ignorance?

**Comment by anicholson44** [comment]
@stevenspiel I'm not aware of any practical problems with `feature` or `background` and we could keep using those if it makes sense.

**Comment by andycandrea** [comment]
I don't personally have much of an opinion here. I think that a good number of our Capybara tests do use `describe`/`it`/etc, so it shouldn't be bad to switch our go-to. Since it seems like we don't really get much out of using the Capybara lingo, I'd vote to go for @anicholson44's suggestion since it'll remove a bit of inconvenience.

**Comment by adam-scimed** [comment]
Resolution: 

Suggestion accepted. Use 'describe', 'context', and 'it' in Capybara tests instead of 'feature' and 'scenario'.

@anicholson44 - Would you update and close?

**Comment by anicholson44** [comment]
see https://github.com/SciMed/style-guide/pull/44
