### ISSUE TITLE
Require a description string in `it` blocks

### ISSUE THREAD

**Issue by jreut** [SciMed/style-guide#35]
Sometimes RSpec will automatically name a test case for you.

``` ruby
describe MyClass do
  it do
    expect { subject.do_an_errory_thing }.to raise_error('with this error text')
  end
end

# approximate RSpec output
#=> "MyClass#do_an_errory_thing expected to raise an error 'with this error text'"
```

Is it preferable to explicitly write a description for the `it` block or to just let RSpec do its magic for us?

@anicholson44

**Comment by andycandrea** [comment]
We typically pass a string to `it` blocks with the exception of shoulda tests, e.g. `it { is_expected.to validate_presence_of :name }`.

**Comment by adam-scimed** [comment]
Resolution: We should name it with a string unless it's a shoulda test block.

@jreut Can you make a merge request to update the style guide and close this issue if you agree?
