### ISSUE TITLE
Log rescued errors

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#37]
When rescuing an error, do so in the following way:

```
rescue SomeError => e
  Rails.logger.error(e.backtrace.join("\n"))
  # custom error handling behavior
end
```

Even if we never take advantage of it, this ensures that we have a record of where/when errors occurred.

**Comment by adam-scimed** [comment]
Agreed!

We may also want to log the error class name and error message.

@andycandrea - Can you update the style guide and close this task?
