### ISSUE TITLE
.vimrc template?

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#38]
There are a few servers we use that have custom .vimrc files on them. It's always nice to have some customization beyond the defaults (line numbers, syntax highlighting, etc), but it probably doesn't make sense for any of us to put our full .vimrc files on a server that we're all going to use (different mappings and plugins and such). Could we come up with a sensible default (maybe even based off of [vim-sensible](https://github.com/tpope/vim-sensible)?) to put on servers when we can?

**Comment by dbernheisel** [comment]
I'm open to it, and we could put it into some ansible scripts when provisioning servers. I'm open to .irbrc or .pryrc files as well.

**Comment by adam-scimed** [comment]
Agreed. Andy do you want to propose the initial version? Bern should be
able to get it in Ansible pretty easily.

Adam

--
Adam Stasio
SciMed Solutions
327 West Main Street
Durham, NC 27701

adam.stasio@scimedsolutions.com
(919) 287-1817
(919) 680-3377 - Fax
--

**Comment by adam-scimed** [comment]
I think this has been taken care of.

@andycandrea can you merge in the merge request and close this task?
