### ISSUE TITLE
prefer `#update` over `#update_attributes`?

### ISSUE THREAD

**Issue by aangott** [SciMed/style-guide#47]
Could we add a guideline to prefer `#update` over `#update_attributes` in Rails 4 and later?

**Comment by emerson-h** [comment]
AFAIK `#update_attributes` is an alias of `#update`, so I'm okay with either, personally.

**Comment by kathleenlan** [comment]
http://api.rubyonrails.org/v4.2/classes/ActiveRecord/Persistence.html#method-i-update

Indeed, `#update_attributes` is an alias of `#update`. I'm also fine with either option.

**Comment by dbernheisel** [comment]
Seems the real ask is to not use aliases when known. I'm all for that.  If that's the case, could we rephrase the style guide item to be more generic, and use `#update` as an example?

**Comment by andycandrea** [comment]
Whenever we get back around to this, we could have a similar question about `assign_attributes` versus `attributes=`.
