### ISSUE TITLE
Suggest freezing memoized objects

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#49]
When we memoize an object, we do so expecting the value of that object will not change (usually). If we freeze that object, we can enforce its immutability explicitly. Take the following case:

```ruby
def start_time
  @start_time ||= Time.zone.now.to_s
end

@errors.each do |error|
  message = start_time
  message << ': '
  message << error
  puts message
end
```

Obviously, this is a very simple case involving bad code, but I think it serves a reasonable example. Each time through the `@errors` loop will mutate the value of `@start_time`, causing more and more malformatted strings to be passed to `puts` as the loop continues. If this were a more complicated bit of code, it can be the case that the mutation is not caught until it causes bad data (if it's even caught then). If we were to change `start_time` to return `@start_time ||= Time.zone.now.to_s.freeze`, the `@errors` loop would raise an exception and ensure the issue is caught immediately by testing.

This might not be a big issue since we already try to avoid in-place modification for reasons of safety, but I think it's worth adding this as a strong suggestion (though not a hard and fast rule) to the style guide.

**Comment by emerson-h** [comment]
This seems like a counter productive guideline in a lot of cases.

In many cases memoization is used to speed performance when there is an expensive operation that needs to be performed, and often it is useful to allow mutation of the result of the expensive operation.  

For instance: 
```
class Bar < ActiveRecord::Base
  def cached_object_name=(name)
    cached_object.name = name
  end

  private def cached_object
    @cached_object ||= generate_cached_object
  end

  private def generate_cached_object
    Foo.where(<some_very_expensive_query>) || <some expensive initialization process>
  end
end
```

Wouldn't it be better to recommend covering the intended behavior (i.e. that subsequent calls produce the expected results) rather than proscribing a very powerful set of use cases?

**Comment by andycandrea** [comment]
I should have specified that I was imagining this guideline to be used for fairly primitive objects such as strings and arrays. I agree that objects with attributes would not fall under this guideline.

**Comment by andycandrea** [comment]
Perhaps it would be good to add a `Performance` section to the guide. It could include suggested use cases for memoization and a line like "Consider freezing memoized objects that are not intended to be mutated".
