### ISSUE TITLE
Seed generator

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#50]
I just happened to see this line in the guide:

> Create a Rails generator that creates a seed file when you create a new model. Opt out of creating seeds, instead of opting in.

I like the idea, but has this ever been done? If so, it'd be nice to have that generator live in this repo.

**Comment by aangott** [comment]
Andy will investigate

**Comment by andycandrea** [comment]
Given that this line has been removed from the guide, I'm closing this issue.
