### ISSUE TITLE
Indentation for thead/tbody

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#56]
I come across this a lot when reviewing code:

```html
<table>
  <thead>
  <tr>
    <th>Name</th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>
```

I prefer the convention of everything being indented once more beyond its parent tag à la: 
```html
<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
```

That said, from what I've gathered, some text editors automatically enforce the first style, so it may be a pain for some people to follow my convention. While my preference would be to go with the simpler rule of "everything gets indented two more spaces than its parent" (which I find simpler and more readable), I think a convention that's a pain in the butt for a significant number of us is less than ideal.

I propose adding one of the following to the guide:

* All HTML/ERB tags should be indented two spaces further than their parent elements.

OR 

* All HTML/ERB tags should be indented two spaces further than their parents except in the following situations:
  * Parent tag is a `thead`
  * Parent tag is a `tbody`

If we go for the second rule, I'd also say that it's worth discussing the following that I've seen multiple times:

```html
<html>
<head>
  ...
</head>

<body>
<main>
  ...
</main>
</body>
</html>
```

as opposed to:

```html
<html>
  <head>
    ...
  </head>

  <body>
    <main>
      ...
    </main>
  </body>
</html>
```

**Comment by emerson-h** [comment]
We'll use the indented form
