### ISSUE TITLE
Ruby 2.6 Infinite Range Syntax

### ISSUE THREAD

**Issue by jessiel-hacke** [SciMed/style-guide#62]
Ruby 2.6 is going to add a new syntax for infinite range:

### Old
```ruby
  42..Float::INFINITY
  #=> 42..Infinity
```

### new
```ruby
  42..
  #=> 42..nil # yes, this is infinite!

  (0..) == (0..nil)
  #=> true
```
The new syntax is cleaner to read/write, but it may allow some mistakes in cases where you don't want it to be an infinite range and you forget the upper limit for the range. Since this new sintax is just a short for `(0..nil)`, I would like suggest the usage of `nil` in our style guide whenever we are using `Ruby 2.6`.

**Comment by andycandrea** [comment]
We will prefer the old syntax moving forward as it is more explicit.
