### ISSUE TITLE
Add SQL style guide

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#9]
Would it be worth having a standard style for writing raw SQL? I came across [this](http://www.sqlstyle.guide/) and thought something like it might be useful to point to from the style guide.

**Comment by willsteinmetz** [comment]
I think it makes sense to have some general rules for SQL. I wouldn't go too crazy like that difficult to read "river" style and getting a little crazy with indenting the joins way far to the right. But there should be a standard of what goes on a new line and what to indent as well as how to name columns and when to set defaults and keys and such.

**Comment by mjs2600** [comment]
What if we just use this one? http://www.sqlstyle.guide/

**Comment by willsteinmetz** [comment]
@mjs2600 That's the one Andy linked to.

**Comment by andycandrea** [comment]
Closed in 62ac50cf59e834907b63d66c9717d7e6b2765fb7
