### ISSUE TITLE
For discussion: one-letter built-in function names

### ISSUE THREAD

**Issue by andreaangott** [SciMed/style-guide#90]
There's a new vulnerability in Rails 4.2 having to do with the use of `escape_javascript`, which is aliased as `j`.  Searching for uses of `j` in a project is pretty difficult.  Adam suggested we consider adding a guideline to avoid the single-letter function aliases.  Let's discuss! 

In our projects, the single-letter aliases we're probably most likely to use are `l` and `t`.

**Comment by andycandrea** [comment]
We have decided to avoid single letter function calls moving forward.
