### ISSUE TITLE
Configure new rubocop rules

### ISSUE THREAD

**Issue by andreaangott** [SciMed/style-guide#96]
Address this message from rubocop:

```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Layout/SpaceAroundMethodCallOperator (0.82)
 - Lint/RaiseException (0.81)
 - Lint/StructNewOverride (0.81)
 - Style/ExponentialNotation (0.82)
```

**Comment by andycandrea** [comment]
We'll enable all cops and use the `scientific` style for `Style/ExponentialNotation`.

**Comment by andreaangott** [comment]
I don't think we actually made these changes to our example config file.  Also we should update `Metrics/LineLength` to be `Layout/LineLength`

**Comment by andreaangott** [comment]
Oh, and we have 2 new rules to decide on:

- Layout/EmptyLinesAroundAttributeAccessor
- Style/SlicingWithRange

**Comment by jeffersonneel** [comment]
There are some more to decide on:

 - Lint/DeprecatedOpenSSLConstant
 - Lint/MixedRegexpCaptureTypes
 - Style/ExponentialNotation
 - Style/RedundantRegexpCharacterClass
 - Style/RedundantRegexpEscape

**Comment by andycandrea** [comment]
To discuss: the `CheckSymbols` config for the `Naming/VariableNumber` cop.

**Comment by andycandrea** [comment]
New cops to discuss:

* rubocop (0.88.0 -> 1.9.1)
Lint/AmbiguousAssignment:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/ambiguous_assignment.rb
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/binary_operator_with_identical_operands.rb
  Enabled: true
Lint/ConstantDefinitionInBlock:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/constant_definition_in_block.rb
  Enabled: true
Lint/DeprecatedConstants:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/deprecated_constants.rb
  Enabled: true
Lint/DuplicateBranch:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/duplicate_branch.rb
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb
  Enabled: true
Lint/DuplicateRequire:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/duplicate_require.rb
  Enabled: true
Lint/DuplicateRescueException:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/duplicate_rescue_exception.rb
  Enabled: true
Lint/EmptyBlock:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/empty_block.rb
  Enabled: true
Lint/EmptyConditionalBody:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/empty_conditional_body.rb
  Enabled: true
Lint/EmptyClass:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/empty_class.rb
  Enabled: true
Lint/EmptyFile:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/empty_file.rb
  Enabled: true
Lint/FloatComparison:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/float_comparison.rb
  Enabled: true
Lint/HashCompareByIdentity:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/hash_compare_by_identity.rb
  Enabled: true
Lint/IdentityComparison:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/identity_comparison.rb
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/lambda_without_literal_block.rb
  Enabled: true
Lint/MissingSuper:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/missing_super.rb
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/no_return_in_begin_end_blocks.rb
  Enabled: true
Lint/NumberedParameterAssignment:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/numbered_parameter_assignment.rb
  Enabled: true
Lint/OrAssignmentToConstant:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/or_assignment_to_constant.rb
  Enabled: true
Lint/OutOfRangeRegexpRef:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/out_of_range_regexp_ref.rb
  Enabled: true
Lint/RedundantDirGlobSort:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/redundant_dir_glob_sort.rb
  Enabled: true
Lint/RedundantSafeNavigation:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/redundant_safe_navigation.rb
  Enabled: true
Lint/SelfAssignment:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/self_assignment.rb
  Enabled: true
Lint/SymbolConversion:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/symbol_conversion.rb
  Enabled: true
Lint/ToEnumArguments:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/to_enum_arguments.rb
  Enabled: true
Lint/TopLevelReturnWithArgument:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/top_level_return_with_argument.rb
  Enabled: true
Lint/TripleQuotes:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/triple_quotes.rb
  Enabled: true
Lint/UnexpectedBlockArity:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/unexpected_block_arity.rb
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/unmodified_reduce_accumulator.rb
  Enabled: true
Lint/UnreachableLoop:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/unreachable_loop.rb
  Enabled: true
Lint/UselessMethodDefinition:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/useless_method_definition.rb
  Enabled: true
Lint/UselessTimes:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/useless_times.rb
  Enabled: true

Layout/BeginEndAlignment:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/layout/begin_end_alignment.rb
  Enabled: true
Layout/EmptyLineAfterMultilineCondition:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/layout/empty_line_after_multiline_condition.rb
  Enabled: true
Layout/SpaceBeforeBrackets:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/layout/space_before_brackets.rb
  Enabled: true

Style/ArgumentsForwarding:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/arguments_forwarding.rb
  Enabled: true
Style/ClassEqualityComparison:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/class_equality_comparison.rb
  Enabled: true
Style/ClassMethodsDefinitions:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/class_methods_definitions.rb
  Enabled: true
Style/CollectionCompact:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/collection_compact.rb
  Enabled: true
Style/CombinableLoops:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/combinable_loops.rb
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/document_dynamic_eval_definition.rb
  Enabled: true
Style/EndlessMethod:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/endless_method.rb
  Enabled: true
Style/ExplicitBlockArgument:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/explicit_block_argument.rb
  Enabled: true
Style/GlobalStdStream:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/global_std_stream.rb
  Enabled: true
Style/HashExcept:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/hash_except.rb
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/if_with_boolean_literal_branches.rb
  Enabled: true
Style/KeywordParametersOrder:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/keyword_parameters_order.rb
  Enabled: true
Style/NegatedIfElseCondition:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/negated_if_else_condition.rb
  Enabled: true
Style/NilLambda:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/nil_lambda.rb
  Enabled: true
Style/OptionalBooleanParameter:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/optional_boolean_parameter.rb
  Enabled: true
Style/RedundantArgument:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/redundant_argument.rb
  Enabled: true
Style/RedundantSelfAssignment:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/redundant_self_assignment.rb
  Enabled: true
Style/SingleArgumentDig:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/single_argument_dig.rb
  Enabled: true
Style/SoleNestedConditional:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/sole_nested_conditional.rb
  Enabled: true
Style/StaticClass:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/static_class.rb
  Enabled: true
Style/StringConcatenation:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/string_concatenation.rb
  Enabled: true
Style/SwapValues:
  https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/swap_values.rb
  Enabled: true

* rubocop-performance (1.7.1 -> 1.9.2)
Performance/ArraySemiInfiniteRangeSlice:
  https://github.com/rubocop-hq/rubocop-performance/blob/master/lib/rubocop/cop/performance/array_semi_infinite_range_slice.rb
  Enabled: true
Performance/BlockGivenWithExplicitBlock:
  https://github.com/rubocop-hq/rubocop-performance/blob/master/lib/rubocop/cop/performance/block_given_with_explicit_block.rb
  Enabled: true
Performance/CollectionLiteralInLoop:
  https://github.com/rubocop-hq/rubocop-performance/blob/master/lib/rubocop/cop/performance/collection_literal_in_loop.rb
  Enabled: true
Performance/ConstantRegexp:
  https://github.com/rubocop-hq/rubocop-performance/blob/master/lib/rubocop/cop/performance/constant_regexp.rb
  Enabled: true
Performance/MethodObjectAsBlock:
  https://github.com/rubocop-hq/rubocop-performance/blob/master/lib/rubocop/cop/performance/method_object_as_block.rb
  Enabled: true
Performance/Sum:
  https://github.com/rubocop-hq/rubocop-performance/blob/master/lib/rubocop/cop/performance/sum.rb
  Enabled: true

* rubocop-rails (2.7.1 -> 2.9.1)
Rails/AfterCommitOverride:
  https://github.com/rubocop-hq/rubocop-rails/blob/master/lib/rubocop/cop/rails/after_commit_override.rb
  Enabled: true
Rails/ArelStar:
  https://github.com/rubocop-hq/rubocop-rails/blob/master/lib/rubocop/cop/rails/arel_star.rb
  Enabled: true
Rails/AttributeDefaultBlockValue:
  https://github.com/rubocop-hq/rubocop-rails/blob/master/lib/rubocop/cop/rails/attribute_default_block_value.rb
  Enabled: true
Rails/OrderById:
  https://github.com/rubocop-hq/rubocop-rails/blob/master/lib/rubocop/cop/rails/order_by_id.rb
  Enabled: true
Rails/SquishedSQLHeredocs:
  https://github.com/rubocop-hq/rubocop-rails/blob/master/lib/rubocop/cop/rails/squished_sql_heredocs.rb
  Enabled: true
Rails/WhereEquals:
  https://github.com/rubocop-hq/rubocop-rails/blob/master/lib/rubocop/cop/rails/where_equals.rb
  Enabled: true
Rails/WhereNot:
  https://github.com/rubocop-hq/rubocop-rails/blob/master/lib/rubocop/cop/rails/where_not.rb
  Enabled: true

* rubocop-rspec (1.42.0 -> 2.1.0)
RSpec/RepeatedIncludeExample:
  https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/repeated_include_example.rb
  Enabled: true
RSpec/StubbedMock:
  https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/stubbed_mock.rb
  Enabled: true

* rubocop-rake (0.5.1)
Rake/ClassDefinitionInTask:
  https://github.com/rubocop-hq/rubocop-rake/blob/master/lib/rubocop/cop/rake/class_definition_in_task.rb
  Enabled: true
Rake/Desc:
  https://github.com/rubocop-hq/rubocop-rake/blob/master/lib/rubocop/cop/rake/desc.rb
  Enabled: true
Rake/DuplicateNamespace:
  https://github.com/rubocop-hq/rubocop-rake/blob/master/lib/rubocop/cop/rake/duplicate_namespace.rb
  Enabled: true
Rake/DuplicateTask:
  https://github.com/rubocop-hq/rubocop-rake/blob/master/lib/rubocop/cop/rake/duplicate_task.rb
  Enabled: true
Rake/MethodDefinitionInTask:
  https://github.com/rubocop-hq/rubocop-rake/blob/master/lib/rubocop/cop/rake/method_definition_in_task.rb
  Enabled: true

* rubocop-md (1.0.1)
